# Generated by Django 3.2.5 on 2022-06-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200)),
                ('group_description', models.TextField()),
                ('group_created_date', models.DateTimeField(auto_now_add=True)),
                ('group_heat', models.IntegerField(default=0)),
                ('group_num_members', models.IntegerField(default=0)),
                ('group_rules', models.TextField()),
                ('num_of_posts', models.IntegerField(default=0)),
                ('group_picture_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField(default=0)),
                ('user_id', models.BigIntegerField(default=0)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_id', models.BigIntegerField(default=0)),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('post_create_time', models.DateTimeField(auto_now_add=True)),
                ('post_heat', models.IntegerField(default=0)),
                ('post_num_comments', models.IntegerField(default=0)),
                ('post_authorId', models.BigIntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
    ]
