# Generated by Django 3.2.5 on 2022-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.TextField(max_length=1000),
        ),
    ]
