# Generated by Django 4.0.5 on 2022-06-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_cover'),
        ),
    ]
