# Generated by Django 4.0.5 on 2022-06-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
