# Generated by Django 4.0.5 on 2022-06-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_cover', models.ImageField(blank=True, null=True, upload_to='movie_cover')),
                ('introduction', models.TextField(blank=True)),
                ('movie_form', models.CharField(blank=True, max_length=100)),
                ('movie_type', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('screenwriter', models.CharField(max_length=100)),
                ('starring', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('heat', models.IntegerField(default=0)),
                ('movie_num_comments', models.IntegerField(default=0)),
            ],
        ),
    ]
