# Generated by Django 4.0.5 on 2022-06-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_movie_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_cover',
            field=models.ImageField(blank=True, null=True, upload_to='movie_cover'),
        ),
    ]
