# Generated by Django 4.0.5 on 2022-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='type',
            new_name='book_type',
        ),
        migrations.AlterField(
            model_name='book',
            name='author_country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
