# Generated by Django 4.0.5 on 2022-06-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='score_num_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
