# Generated by Django 3.2.5 on 2022-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reporter_id', models.BigIntegerField(default=0)),
                ('comment_id', models.BigIntegerField(default=0)),
            ],
        ),
    ]
