# Generated by Django 3.2.5 on 2022-06-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
